
package br.com.msfu.gui;

import br.com.msfu.sonar.BateriaExecucoesSonar;
import br.com.msfu.sonar.ParametrosSonar;
import java.awt.Dialog;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author rudieri
 */
public class JAgendadorTestes extends javax.swing.JFrame {

    private BateriaExecucoesSonar bateriaExecucoesSonar;
    /**
     * Creates new form JAgendadorTestes
     */
    public JAgendadorTestes() {
        init();
        bateriaExecucoesSonar = new BateriaExecucoesSonar();
        
    }

    private void init() {
        initComponents();
        inicializaTabela();
    }
    
    private void adicionarTeste(){
        JAnalisadorLinter jAnalisadorLinters = new JAnalisadorLinter(this, Dialog.ModalityType.DOCUMENT_MODAL, true);
        jAnalisadorLinters.setVisible(true);
        ParametrosSonar parametros = jAnalisadorLinters.getParametros();
        if (parametros != null) {
            bateriaExecucoesSonar.agendarExecucao(parametros);
            atualizarTabela();
        }
    }
    private void removerTeste(){
        
    }
    
    private void inicializaTabela(){
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addColumn("Projeto");
        tm.addColumn("Perfil");
        tm.addColumn("Nº Testes");
        tm.addColumn("Obj");
        jTable1.removeColumn(jTable1.getColumn("Obj"));
    }
    
    private void atualizarTabela(){
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        HashSet<ParametrosSonar> execucoesAgendadas = bateriaExecucoesSonar.getExecucoesAgendadas();
        for (ParametrosSonar param : execucoesAgendadas) {
            Object[] row = new Object[tm.getColumnCount()];
            row[0] = param.getProjeto();
            row[1] = param.getPerfil().getNome();
            row[2] = param.getNroTestes();
            row[3] = param;
            tm.addRow(row);
        }
    }
    
    
    private void iniciarTestes(){
        try {
            bateriaExecucoesSonar.iniciar();
            String textoCsv = bateriaExecucoesSonar.getTextoCsv();
            System.out.println("--------------------------------");
            System.out.println("----------RESULTADOS------------");
            System.out.println(textoCsv);
            System.out.println("--------------------------------");
            System.out.println("--------------------------------");
            
        } catch (IOException | SQLException | InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao executar testes" + ex.getMessage());
            Logger.getLogger(JAgendadorTestes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Rem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCellSelectionEnabled(false);
        jTable1.setRowSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(42, 336));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton_Add.setText("+");
        jButton_Add.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButton_Add.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_Add.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_Add.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);

        jButton_Rem.setText("-");
        jButton_Rem.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButton_Rem.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_Rem.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_Rem.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton_Rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Rem);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jButton1.setText("Iniciar Testes");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(918, 366));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        adicionarTeste();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_RemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemActionPerformed
        removerTeste();
    }//GEN-LAST:event_jButton_RemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciarTestes();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAgendadorTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAgendadorTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAgendadorTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAgendadorTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAgendadorTestes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Rem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
