git clone https://github.com/JetBrains/intellij-community.git
git clone https://github.com/android/platform_frameworks_base.git
git clone https://github.com/daniulive/SmarterStreaming.git
git clone https://github.com/processing/processing.git
git clone https://github.com/claritylab/lucida.git
git clone https://github.com/apereo/cas.git
git clone https://github.com/libgdx/libgdx.git
git clone https://github.com/facebook/buck.git
git clone https://github.com/apache/hadoop.git
git clone https://github.com/JetBrains/kotlin.git
git clone https://github.com/bazelbuild/bazel.git
git clone https://github.com/elastic/elasticsearch.git
git clone https://github.com/neo4j/neo4j.git
git clone https://github.com/actorapp/actor-platform.git
git clone https://github.com/NLPchina/ansj_seg.git
git clone https://github.com/java-native-access/jna.git
git clone https://github.com/OpenRefine/OpenRefine.git
git clone https://github.com/stanfordnlp/CoreNLP.git
git clone https://github.com/gocd/gocd.git
git clone https://github.com/facebook/litho.git
git clone https://github.com/apache/cassandra.git
git clone https://github.com/zxing/zxing.git
git clone https://github.com/serge-rider/dbeaver.git
git clone https://github.com/openhab/openhab1-addons.git
git clone https://github.com/orientechnologies/orientdb.git
git clone https://github.com/naver/pinpoint.git
git clone https://github.com/yixia/VitamioBundle.git
git clone https://github.com/gradle/gradle.git
git clone https://github.com/zaproxy/zaproxy.git
git clone https://github.com/apache/storm.git
git clone https://github.com/google/guava.git
git clone https://github.com/hibernate/hibernate-orm.git
git clone https://github.com/afollestad/material-dialogs.git
git clone https://github.com/deeplearning4j/deeplearning4j.git
git clone https://github.com/haifengl/smile.git
git clone https://github.com/lipangit/JieCaoVideoPlayer.git
git clone https://github.com/stephanenicolas/robospice.git
git clone https://github.com/twitter/heron.git
git clone https://github.com/google/closure-compiler.git
git clone https://github.com/druid-io/druid.git
git clone https://github.com/WhisperSystems/Signal-Android.git
git clone https://github.com/aa112901/remusic.git
git clone https://github.com/qii/weiciyuan.git
git clone https://github.com/HotBitmapGG/bilibili-android-client.git
git clone https://github.com/dropbox/hackpad.git
git clone https://github.com/airbnb/lottie-android.git
git clone https://github.com/Atmosphere/atmosphere.git
git clone https://github.com/pedrovgs/DraggablePanel.git
git clone https://github.com/alibaba/jstorm.git
git clone https://github.com/spring-projects/spring-framework.git
git clone https://github.com/Nightonke/BoomMenu.git
git clone https://github.com/eclipse/vert.x.git
git clone https://github.com/motianhuo/wechat.git
git clone https://github.com/thinkaurelius/titan.git
git clone https://github.com/jeasonlzy/okhttp-OkGo.git
git clone https://github.com/puniverse/quasar.git
git clone https://github.com/Alluxio/alluxio.git
git clone https://github.com/ChrisRM/material-theme-jetbrains.git
git clone https://github.com/mybatis/mybatis-3.git
git clone https://github.com/prestodb/presto.git
git clone https://github.com/iBotPeaches/Apktool.git
git clone https://github.com/commonsguy/cw-omnibus.git
git clone https://github.com/rzwitserloot/lombok.git
git clone https://github.com/alibaba/freeline.git
git clone https://github.com/roboguice/roboguice.git
git clone https://github.com/wasabeef/recyclerview-animators.git
git clone https://github.com/Yalantis/uCrop.git
git clone https://github.com/chentao0707/SimplifyReader.git
git clone https://github.com/google/guice.git
git clone https://github.com/antlr/antlr4.git
git clone https://github.com/CymChad/BaseRecyclerViewAdapterHelper.git
git clone https://github.com/alibaba/atlas.git
git clone https://github.com/apache/zeppelin.git
git clone https://github.com/Graylog2/graylog2-server.git
git clone https://github.com/facebook/fresco.git
git clone https://github.com/spring-projects/spring-boot.git
git clone https://github.com/pengjianbo/GalleryFinal.git
git clone https://github.com/realm/realm-java.git
git clone https://github.com/yanzhenjie/NoHttp.git
git clone https://github.com/apache/kafka.git
git clone https://github.com/eclipse/che.git
git clone https://github.com/google/flexbox-layout.git
git clone https://github.com/dropwizard/dropwizard.git
git clone https://github.com/netty/netty.git
git clone https://github.com/hankcs/HanLP.git
git clone https://github.com/k9mail/k-9.git
git clone https://github.com/alibaba/druid.git
git clone https://github.com/google/ExoPlayer.git
git clone https://github.com/davemorrissey/subsampling-scale-image-view.git
git clone https://github.com/pili-engineering/PLDroidPlayer.git
git clone https://github.com/mockito/mockito.git
git clone https://github.com/google/j2objc.git
git clone https://github.com/google/error-prone.git
git clone https://github.com/JackyAndroid/AndroidInterview-Q-A.git
git clone https://github.com/google/iosched.git
git clone https://github.com/ReactiveX/RxJava.git
git clone https://github.com/roughike/BottomBar.git
git clone https://github.com/lingochamp/FileDownloader.git
git clone https://github.com/yahoo/anthelion.git
git clone https://github.com/wyouflf/xUtils.git
